      - name: Build emulator
        run: |
          mkdir build && cd build
          cmake -GNinja -DCMAKE_BUILD_TYPE=Release -DPORTABLE=1 -DCMAKE_C_COMPILER=clang -DCMAKE_CXX_COMPILER=clang++ ..
          ninja -v emulator